version: '3.4'

services:
  favodemel.api:
    container_name: favodemel.api
    image: ${DOCKER_REGISTRY-}favodemelapi
    build:
      context: ./api
      dockerfile: src/FavoDeMel.API/Dockerfile      
    depends_on:
      - favodemel.db
      - rabbitmq
    networks:
      - favomel-network

  favodemel.db:
    container_name: favodemel.db
    build: 
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - mssqldata:/var/opt/mssql
    networks:
      - favomel-network

  rabbitmq:
    container_name: favodemel.rabbitmq
    image: rabbitmq:3-management
    networks:
      - favomel-network
    volumes:   
      - "./rabbitmq/rabbitmq.plugins:/etc/rabbitmq/enabled_plugins"
      - "./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json"

networks:
  favomel-network:
    driver: bridge

volumes:
  mssqldata: