FROM node:alpine as builder

ARG env=prod

RUN apk update && apk add --no-cache make git

WORKDIR /app
COPY package.json package-lock.json  /app/
RUN npm set strict-ssl false
RUN npm install @angular/cli -g
RUN cd /app && npm install
COPY .  /app

RUN cd /app && npm run build -- --output-path=./dist/out

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY nginx.conf /etc/nginx/nginx.conf
RUN ls -a
COPY --from=builder /app/dist/out /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]